name: dio_cache_interceptor_objectbox_store
description: A DB cache store implementation with ObjectBox for dio_cache_interceptor package.
version: 1.2.0
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_objectbox_store

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  dio_cache_interceptor: ^3.3.0
  # https://pub.dev/packages/objectbox
  objectbox: ^2.0.0
  # https://pub.dev/packages/flat_buffers
  flat_buffers: ^2.0.5

# dependency_overrides:
#   dio_cache_interceptor:
#     path: ../dio_cache_interceptor

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.4
  # https://pub.dev/packages/objectbox_generator
  objectbox_generator: any
  # https://pub.dev/packages/lints
  lints: ^2.1.0
  # https://pub.dev/packages/test
  test: ^1.24.3